backend:
  name: git-gateway               # use GitHub directly
  repo: https://github.com/Saqibworksehsan/S82Studio   # ← CHANGE
  branch: main
media_folder: public/img/projects
public_folder: /img/projects
collections:
  - name: projects
    label: Projects
    folder: content/projects
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Location, name: location, widget: string }
      - { label: Thumbnail, name: thumbnail, widget: image }
      - { label: Gallery, name: images, widget: list, field: { label: Image, name: image, widget: image } }
      - { label: Body, name: body, widget: markdown, required: false }